name: Go tests

on:
  pull_request:
    branches: 
    - master
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Run go lint, test & build
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: make go-lint-install && make lint && make test && make build-linux
