name: Go tests

on:
  pull_request:
    branches: 
    - master
 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Run go lint
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: make lint
      
    - name: Run go test
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: make test

    - name: Run go build
      uses: cedrickring/golang-action@1.4.1
      env:
        GO111MODULE: "on"
      with:
        args: make build-linux
